# Generated by Django 4.0.3 on 2023-03-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtb',
            name='reviews_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtb',
            name='reviews_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
