# Generated by Django 4.1.3 on 2023-03-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0003_alter_tbjobs_options_alter_tbsource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTrustpilotReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('trustpilot_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.CharField(blank=True, max_length=100, null=True)),
                ('consumer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_info', models.JSONField(blank=True, null=True)),
                ('reply', models.JSONField(blank=True, null=True)),
                ('hash', models.CharField(max_length=500, unique=True)),
                ('scraped_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_trustpilot_reviews',
                'managed': False,
            },
        ),
    ]
