# Generated by Django 4.0.3 on 2023-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbJobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('reviews_from_date', models.DateTimeField(blank=True, null=True)),
                ('reviews_to_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('execution_start_date', models.DateTimeField(blank=True, null=True)),
                ('execution_end_date', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500, unique=True)),
                ('path_to_file', models.TextField()),
                ('url_to_file', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100, unique=True)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbTripadvisorReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('user_info', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_info', models.JSONField(blank=True, null=True)),
                ('social_statistics', models.JSONField(blank=True, null=True)),
                ('owner_response', models.JSONField(blank=True, null=True)),
                ('hash', models.CharField(max_length=500, unique=True)),
                ('scraped_data', models.DateTimeField()),
                ('tripadvisor_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_tripadvisor_reviews',
                'managed': False,
            },
        ),
    ]
