# Generated by Django 4.0.3 on 2023-03-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbjobs',
            options={'managed': True},
        ),
    ]
