# Generated by Django 4.0.3 on 2023-03-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_alter_tbjobs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbjobs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbsource',
            options={'managed': True},
        ),
    ]
